export const EVENTS_LIST_REQUEST = "EVENTS_LIST_REQUEST";
export const EVENTS_LIST_SUCCESS = "EVENTS_LIST_SUCCESS";
export const EVENTS_LIST_FAIL = "EVENTS_LIST_FAIL";
export const FILTER_CAT_CHANGE = "FILTER_CAT_CHANGE";
export const FILTER_TYPE_CHANGE = "FILTER_TYPE_CHANGE";
export const EVENTS_ADD_REQUEST = "EVENTS_ADD_REQUEST";
export const EVENTS_ADD_SUCCESS = "EVENTS_ADD_SUCCESS";
export const EVENTS_ADD_FAIL = "EVENTS_ADD_FAIL";